// Auto-generated by app_hugo_panel/utils/cf_pages.py. Do not edit by hand.
const _nf = async (request, env) => {
  // Serve the site's 404.html body under a 404 status. Falls back to the
  // bare-string form only if env.ASSETS isn't available or /404.html isn't
  // shipped — that fallback used to be the whole response, and stuck out
  // as a fingerprint of the click-gate Function.
  try {
    const r = await env.ASSETS.fetch(new URL('/404.html', request.url).toString());
    return new Response(r.body, { status: 404, headers: r.headers });
  } catch (_) {
    return _nf(request, env);
  }
};

export const onRequest = async ({ request, env }) => {
  const ua = (request.headers.get('user-agent') || '').toLowerCase();
  const BOT = /(gptbot|chatgpt|claudebot|anthropic|perplexitybot|amazonbot|bytespider|ccbot|google-extended|applebot-extended|duckassistbot|cohere-ai|meta-externalagent|bot|crawl|spider|scraper|preview|http-client|curl|wget|python-requests|python-urllib|node-fetch|okhttp)/i;
  if (BOT.test(ua)) return _nf(request, env);

  // Only accept token requests initiated FROM our own page (the click-gate
  // JS runs there on hover/touch/focus). A direct-URL scraper fetching
  // /<token>/ from a fresh tab gets sec-fetch-site=none → refuse.
  const sfs = request.headers.get('sec-fetch-site');
  if (sfs && sfs !== 'same-origin' && sfs !== 'same-site') {
    return _nf(request, env);
  }

  const cookieName = env.COOKIE_NAME;
  const hmacKey = env.HMAC_KEY;
  const playPath = env.PLAY_PATH;
  if (!cookieName || !hmacKey || !playPath) return _nf(request, env);

  const ts = String(Math.floor(Date.now() / 1000));
  const key = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(hmacKey),
    { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(ts));
  const sigHex = Array.from(new Uint8Array(sig))
    .map(b => b.toString(16).padStart(2, '0')).join('').slice(0, 16);
  const value = `${ts}.${sigHex}`;

  return new Response('', {
    status: 204,
    headers: {
      'Set-Cookie': `${cookieName}=${value}; Path=/${playPath}/; SameSite=Strict; Max-Age=30; Secure`,
      'Cache-Control': 'no-store',
    },
  });
};
