// Auto-generated by app_hugo_panel/utils/cf_pages.py. Do not edit by hand.
export const onRequest = async ({ request, env }) => {
  try {
    const r = await env.ASSETS.fetch(new URL('/404.html', request.url).toString());
    return new Response(r.body, { status: 404, headers: r.headers });
  } catch (_) {
    return new Response('Not Found', { status: 404 });
  }
};
