name = "spinmama-bet-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmama-bet.at"
HMAC_KEY = "94726cb8215e94f525be5532b1ba0d69e2be9477f642d4c5109b6f810fda9ec0"
COOKIE_NAME = "nfa"
PLAY_PATH = "begin"
BUTTON_ID = "pd1996931536a3fd206b8db3b95823df3"
GATE_SALT = "a22c2b75cc113f06"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "lz3n"
CTA_SELECTOR = ".play-button"
