// Auto-generated by app_hugo_panel/utils/cf_pages.py. Do not edit by hand.
const _nf = async (request, env) => {
  try {
    const r = await env.ASSETS.fetch(new URL('/404.html', request.url).toString());
    return new Response(r.body, { status: 404, headers: r.headers });
  } catch (_) {
    return new Response('Not Found', { status: 404 });
  }
};

const _clean = (v) => (v || '').replace(/[\x00-\x1f\x7f]/g, '').trim();

const _shuffle = (a) => {
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const t = a[i]; a[i] = a[j]; a[j] = t;
  }
  return a;
};

// Destination refused unless https and not a redirector/ref/this site host.
const _allowed = (dest, nodes, refUrl, siteHost) => {
  let p;
  try { p = new URL(dest); } catch (_) { return false; }
  if (p.protocol !== 'https:') return false;
  const host = p.hostname.toLowerCase();
  const forbidden = [siteHost.toLowerCase()];
  for (const n of nodes) { try { forbidden.push(new URL(n).hostname.toLowerCase()); } catch (_) {} }
  try { if (refUrl) forbidden.push(new URL(refUrl).hostname.toLowerCase()); } catch (_) {}
  for (const bad of forbidden) {
    if (bad && (host === bad || host.endsWith('.' + bad))) return false;
  }
  return true;
};

// Ask one node. Returns {location, cookie, maxAge} on a redirect.
// Throws {next:true} when the request provably never reached the node (try next),
// {next:false} on a definitive non-redirect OR timeout (stop — the node may have
// recorded the click already, re-asking would double-count).
const _askNode = async (url, headers, timeoutMs) => {
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), timeoutMs);
  let resp;
  try {
    resp = await fetch(url, { method: 'GET', redirect: 'manual', headers, signal: ctl.signal });
  } catch (_) {
    throw { next: !ctl.signal.aborted };
  } finally {
    clearTimeout(timer);
  }
  const s = resp.status;
  if (s === 521 || s === 522 || s === 523 || s === 525 || s === 526) throw { next: true };
  const loc = resp.headers.get('location') || '';
  if (s < 300 || s > 399 || !loc) throw { next: false };
  return {
    location: loc,
    cookie: resp.headers.get('x-uniqueness-cookie') || '',
    maxAge: parseInt(resp.headers.get('x-cookie-max-age') || '0', 10) || 0,
  };
};

const _unavailable = () => new Response(
  '<!doctype html><meta charset="utf-8"><title>Please try again</title>'
  + '<p style="font:16px/1.5 system-ui;margin:3rem auto;max-width:30rem;text-align:center">'
  + 'This link is temporarily unavailable. Please try again in a minute.</p>',
  { status: 503, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } }
);

export const onRequest = async ({ request, env }) => {
  const ua = (request.headers.get('user-agent') || '').toLowerCase();
  const BOT = /(gptbot|chatgpt|claudebot|anthropic|perplexitybot|amazonbot|bytespider|ccbot|google-extended|applebot-extended|duckassistbot|cohere-ai|meta-externalagent|bot|crawl|spider|scraper|preview|http-client|curl|wget|python-requests|python-urllib|node-fetch|okhttp)/i;
  if (BOT.test(ua)) return _nf(request, env);

  // Only real top-level navigations from OUR own page. Both headers are
  // on the forbidden-header list — JS can't spoof either. Absent (old
  // browsers) = allow, for compat.
  const sfd = request.headers.get('sec-fetch-dest');
  if (sfd && sfd !== 'document') return _nf(request, env);
  const sfs = request.headers.get('sec-fetch-site');
  if (sfs && sfs !== 'same-origin' && sfs !== 'same-site') return _nf(request, env);

  const cookieName = env.COOKIE_NAME;
  if (!cookieName) return _nf(request, env);
  const m = (request.headers.get('cookie') || '').match(new RegExp('(?:^|;\\s*)' + cookieName + '=([^;]+)'));
  if (!m) return _nf(request, env);

  const [tsStr, sigHex] = m[1].split('.');
  const ts = parseInt(tsStr, 10);
  const now = Math.floor(Date.now() / 1000);
  if (!Number.isFinite(ts) || !sigHex || (now - ts) > 30 || (now - ts) < -5) {
    return _nf(request, env);
  }

  const key = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(env.HMAC_KEY),
    { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const expected = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(tsStr));
  const expectedHex = Array.from(new Uint8Array(expected))
    .map(b => b.toString(16).padStart(2, '0')).join('').slice(0, 16);
  if (sigHex !== expectedHex) return _nf(request, env);

  // Redirector roster is mandatory. No fallback to a direct REF_URL nav —
  // that was the old pre-redirector shape and must stay dead.
  let nodes;
  try { nodes = JSON.parse(env.GO_URLS || '[]'); } catch (_) { nodes = []; }
  if (!Array.isArray(nodes) || !nodes.length || !env.GO_TOKEN || !env.REF_URL) {
    return _unavailable();
  }

  // Labels on the /play link itself (utm_* / sub_id_*) ride along; the
  // referral link's own query still wins on the redirector side.
  const url = new URL(request.url);
  const qs = new URLSearchParams();
  for (const [k, v] of url.searchParams) {
    if (/^(utm_[a-z_]+|sub_id_\d+)$/.test(k)) qs.set(k, v);
  }
  const suffix = qs.toString() ? ('?' + qs.toString()) : '';

  const goCookie = env.GO_COOKIE || '';
  const cookieHdr = request.headers.get('cookie') || '';
  const gc = goCookie
    ? cookieHdr.match(new RegExp('(?:^|;\\s*)' + goCookie + '=([^;]+)'))
    : null;

  const siteHost = url.hostname.replace(/^www\./, '');
  const headers = {};
  const put = (n, val) => { const c = _clean(val); if (c) headers[n] = c; };
  put('X-Request-Token', env.GO_TOKEN);
  put('X-Request-Ref', env.REF_URL);
  put('X-Request-Site', siteHost);
  put('X-Visitor-IP', request.headers.get('CF-Connecting-IP'));
  put('X-Visitor-UA', request.headers.get('user-agent'));
  put('X-Visitor-Lang', (request.headers.get('accept-language') || '').slice(0, 5));
  put('X-Visitor-Country', request.headers.get('CF-IPCountry'));
  put('X-Visitor-Cookie', gc ? gc[1] : '');
  put('X-Visitor-Referer', request.headers.get('referer'));

  let answer = null;
  for (const node of _shuffle(nodes.slice())) {
    try {
      answer = await _askNode(node + suffix, headers, 9000);
      break;
    } catch (e) {
      if (e && e.next) continue;  // provably unreachable → try next
      return _unavailable();      // definitive non-redirect / timeout → stop
    }
  }
  if (!answer || !_allowed(answer.location, nodes, env.REF_URL, siteHost)) {
    return _unavailable();
  }

  const respHeaders = {
    'content-type': 'text/html; charset=utf-8',
    'cache-control': 'no-store, private',
  };
  if (goCookie && answer.cookie) {
    const secs = answer.maxAge > 0 ? answer.maxAge : 86400;
    respHeaders['set-cookie'] = goCookie + '=' + answer.cookie
      + '; Path=/; Max-Age=' + secs + '; Secure; HttpOnly; SameSite=Lax';
  }
  const target = answer.location;
  const jsUrl = JSON.stringify(target);
  const htmlUrl = target.replace(/&/g, '&amp;').replace(/"/g, '&quot;')
                        .replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const html = '<!doctype html><meta charset="utf-8">'
    + '<meta name="referrer" content="no-referrer">'
    + '<meta http-equiv="refresh" content="0;url=' + htmlUrl + '">'
    + '<script>location.replace(' + jsUrl + ')</script>';
  return new Response(html, { status: 200, headers: respHeaders });
};
