// Auto-generated by app_hugo_panel/utils/cf_pages.py. Do not edit by hand.
const _nf = async (request, env) => {
  // Serve the site's 404.html body under a 404 status. Falls back to the
  // bare-string form only if env.ASSETS isn't available or /404.html isn't
  // shipped — that fallback used to be the whole response, and stuck out
  // as a fingerprint of the click-gate Function.
  try {
    const r = await env.ASSETS.fetch(new URL('/404.html', request.url).toString());
    return new Response(r.body, { status: 404, headers: r.headers });
  } catch (_) {
    return _nf(request, env);
  }
};

export const onRequest = async ({ request, env }) => {
  const ua = (request.headers.get('user-agent') || '').toLowerCase();
  const BOT = /(gptbot|chatgpt|claudebot|anthropic|perplexitybot|amazonbot|bytespider|ccbot|google-extended|applebot-extended|duckassistbot|cohere-ai|meta-externalagent|bot|crawl|spider|scraper|preview|http-client|curl|wget|python-requests|python-urllib|node-fetch|okhttp)/i;
  if (BOT.test(ua)) return _nf(request, env);

  // Only real top-level navigations from OUR own page. Both headers are
  // on the forbidden-header list — JS can't spoof either. Absent header
  // (old browsers) = allow, for compat.
  //   sec-fetch-dest=document  → real address-bar/click nav, not fetch/xhr
  //   sec-fetch-site=same-*    → came from a link on our own domain, not
  //                              a direct-URL scraper or foreign referrer
  const sfd = request.headers.get('sec-fetch-dest');
  if (sfd && sfd !== 'document') return _nf(request, env);
  const sfs = request.headers.get('sec-fetch-site');
  if (sfs && sfs !== 'same-origin' && sfs !== 'same-site') {
    return _nf(request, env);
  }

  const cookieName = env.COOKIE_NAME;
  if (!cookieName) return _nf(request, env);
  const m = (request.headers.get('cookie') || '').match(new RegExp('(?:^|;\\s*)' + cookieName + '=([^;]+)'));
  if (!m) return _nf(request, env);

  const [tsStr, sigHex] = m[1].split('.');
  const ts = parseInt(tsStr, 10);
  const now = Math.floor(Date.now() / 1000);
  if (!Number.isFinite(ts) || !sigHex || (now - ts) > 30 || (now - ts) < -5) {
    return _nf(request, env);
  }

  const key = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(env.HMAC_KEY),
    { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const expected = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(tsStr));
  const expectedHex = Array.from(new Uint8Array(expected))
    .map(b => b.toString(16).padStart(2, '0')).join('').slice(0, 16);
  if (sigHex !== expectedHex) return _nf(request, env);

  const target = env.REF_URL;
  if (!target) return _nf(request, env);

  // Client-side redirect (not HTTP 302) so the affiliate URL never rides
  // a Location header — fetch(...).url stays blind. Meta-refresh handles
  // the JS-off path; location.replace does not add a history entry.
  const jsUrl   = JSON.stringify(target);
  const htmlUrl = target.replace(/&/g, '&amp;').replace(/"/g, '&quot;')
                        .replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const html = '<!doctype html><meta http-equiv="refresh" content="0;url='
             + htmlUrl + '"><script>location.replace(' + jsUrl + ')</script>';
  return new Response(html, {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store, private',
    },
  });
};
